services:
  redis:
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data

  redisinsight:
    image: redis/redisinsight:latest
    restart: unless-stopped
    environment:
      RI_DB_HOST: redis
      RI_DB_PORT: 6379
      RI_DB_NAME: msg
    volumes:
      - redisinsight_data:/data
    depends_on:
      - redis

  app:
    build: .
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      REDIS_URL: redis://redis:6379
    depends_on:
      - redis
  storage:
    image: minio/minio:latest
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - storage_data:/data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
      MINIO_API_CORS_ALLOWED_ORIGINS: "http://localhost:8080"
    command: server /data --console-address ":9001"
volumes:
  redis_data:
  redisinsight_data:
  storage_data:
